# Site settings
title: Mark Csizmadia - Personal Website
author:
  name: Mark Csizmadia
  email: mark.antal.csizmadia@gmail.com
description: "Mark Csizmadia's personal website"

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one